# -*- coding: utf-8 -*-
"""
System state definition for AADL to ROS2 conversion system
"""

from typing import Dict, List, TypedDict


class SystemState(TypedDict):
    """Global system state for AADL to ROS2 conversion pipeline"""
    # input arguments
    aadl_file_path: str  # Path to the AADL file
    aadl_file_name: str  # Name of the AADL file
    system_name: str  # Name of the system to convert
    output_dir: str  # Output directory for generated code
    api_key: str  # LLM API key for code generation (optional, can also use DEEPSEEK_API_KEY env variable)
    
    # output files
    xml_file_path: str  # Path to the XML file generated by the parser
    ros2_arch: Dict  # ROS2 architecture JSON
    ros2_arch_file: str  # Architecture contract with ROS2 advanced features (QoS, concurrency locks)
    # test report files
    dynamic_test_report: str  # Path to the dynamic test report file
    topic_validation_report: str  # Path to the topic validation report file
    
    # error messages
    patched_timing: List[str]  # Error messages from timeout warnings
    dynamic_test_errors: List[Dict]  # Normalized error messages from dynamic compilation and testing tool
    runtime_analysis_errors: List[Dict]  # Error messages from runtime analysis tool
    error_types: List[str]  # Error types from dynamic testing (e.g., "SyntaxError", "TimingViolation")
    # updated node
    current_node: str  # Current execution node name
